### PR TITLE
Activity integration

### PR DESCRIPTION
**Pull request by oliveiraigorm**

### CODE REVIEW

**Comment by oliveiraigorm** [comment]
@frozenbanana @mwalbeck There are a lot of formatting changes from Visual Code that makes reviewing hard, what can I do to improve it?

**Comment by mwalbeck** [comment]
I've just pushed a quick commit disabling formatOnSave in the repo, and also added the relevant paths so all the Nextcloud related function are properly recognised. That should make it a bit easier to work with. Then we can figure out how exactly we want to approach formatting and things in this repo going forward.

On another note, other than adding the time of the booking in the activity entry, this pull request looks good to me!

**Comment by oliveiraigorm** [comment]
New format of the events:

image

**Review by mwalbeck — APPROVED** [review]
Very nice!

**Pull request merged**
