### PR TITLE
New email template

### PR DESCRIPTION
**Pull request by mwalbeck**
This pull request is dependent on https://github.com/MetaProvide/adminly_core/pull/67

### CODE REVIEW

**Comment by oliveiraigorm** [comment]
I'm having issues testing it. I have adminly core on the main branch currently
image

**Comment by mwalbeck** [comment]
@oliveiraigorm If you run the following command in the devkit, what output do you get?

```
docker-compose exec -u www-data nextcloud php occ config:system:get mail_template_class
```

**Comment by oliveiraigorm** [comment]
> @oliveiraigorm If you run the following command in the devkit, what output do you get?
> 
> ```
> docker-compose exec -u www-data nextcloud php occ config:system:get mail_template_class
> ```

No output

**Comment by mwalbeck** [comment]
Then running the following command should fix it

```
docker-compose exec -u www-data nextcloud php occ config:system:set --value="OCA\\Adminly_Core\\Mail\\EMailTemplate" mail_template_class
```

**Comment by oliveiraigorm** [comment]
> Then running the following command should fix it
> 
> ```
> docker-compose exec -u www-data nextcloud php occ config:system:set --value="OCA\\Adminly_Core\\Mail\\EMailTemplate" mail_template_class
> ```

Same issue :(

**Comment by mwalbeck** [comment]
And does the previous command give an output this time around?

**Comment by oliveiraigorm** [comment]
> And does the previous command give an output this time around?

Still no output

**Comment by mwalbeck** [comment]
> > And does the previous command give an output this time around?
> 
> Still no output

Are you running the command in the correct folder? It should be run in adminly_devkit

**Review by oliveiraigorm — APPROVED** [review]

**Pull request merged**
